name: C/C++ CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'davidgiven/cpm65'

    - name: apt
      run: sudo apt update && sudo apt install cc1541 cpmtools libfmt-dev fp-compiler moreutils mame srecord 64tass libreadline-dev libelf-dev

    - name: install llvm-mos
      run: |
        wget -q -O - https://github.com/llvm-mos/llvm-mos-sdk/releases/latest/download/llvm-mos-linux.tar.xz | tar xJf - -C $HOME

    - name: install roms
      run: |
        sh scripts/get-roms.sh

    #- name: Setup upterm session
    #  uses: lhotari/action-upterm@v1
    #  with:
    #    limit-access-to-actor: true

    - name: make
      run: make LLVM=$HOME/llvm-mos/bin +all +mametest

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}.${{ github.sha }}
        path: |
          images/apple2e.po
          images/apple2e_b.po
          images/atari800.atr
          images/atari800b.atr
          images/atari800c.atr
          images/atari800hd.atr
          images/atari800xlhd.atr
          images/bbcmicro.ssd
          images/c64.d64
          images/diskdefs
          images/kim-1-iec.zip
          images/kim-1-k1013.zip
          images/kim-1-sdcard.zip
          images/kim-1-sdshield.zip
          images/neo6502.zip
          images/oric.dsk
          images/osi400f.os8
          images/osi400mf.os5
          images/osi500f.os8
          images/osi500mf.os5
          images/osi600f.os8
          images/osi600mf.os5
          images/osi600mf80.osi
          images/osif-b.os8
          images/osimf-b.os5
          images/osimf-c.os5
          images/osimf-d.os5
          images/osimf80-b.osi
          images/osimf80-c.os
          images/osimf80-d.osi
          images/osiserf.os8
          images/pet4032.d64
          images/pet8032.d64
          images/pet8096.d64
          images/snes.smc
          images/x16.zip
          images/vic20_iec.d64
          images/vic20_yload.d64

